ARG RHBK_IMAGE
FROM ${RHBK_IMAGE} AS builder

COPY target/rhbk-theme-botelho-1.2.5.jar /opt/keycloak/providers/rhbk-theme-botelho.jar

# Build the optimized server image after adding providers/themes.
RUN /opt/keycloak/bin/kc.sh build

FROM ${RHBK_IMAGE}
COPY --from=builder /opt/keycloak/ /opt/keycloak/
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
