parent=keycloak.v2
styles=css/admin-1.2.2.css
darkMode=true
contentHashPattern=assets/.*
logo=/img/botelho-identity-logo.svg
logoUrl=
favIcon=/img/favicon.svg
favIconType=image/svg+xml
title=Botelho Identity | Administração
description=Console corporativo de identidade e acesso.
