parent=keycloak.v2
import=common/keycloak
styles=css/styles.css css/brand-1.2.3.css
scripts=js/brand-1.2.3.js
favicons.svg=img/favicon.svg
locales=en,pt-BR
darkMode=true
meta=robots==noindex,nofollow
